### ISSUE TITLE
Possibility of getting source code hosted here as well?

### ISSUE THREAD

**Issue by JohnEricson** [SPECUSA/SelfServiceBI#1]
This project looks very promising and I'm considering using it in a project where I wan't to allow my users to more easily make their own dashboards.
Is there any possibility we could get the source code hosted here so we more easily could contribute code to it?

Thanks,
John

**Comment by SPECUSA** [comment]
Hi John,

We don't have any issue over that , but before move forward with anything, we would like to discuss what kind of change/Features that you want to add.

Because , we are also continuously adding the features and not want to effort clashing.

My SkypeID is :  pranav.lakhani.specindia

Let's setup the call for better engage.

Thanks, Pranav

**Comment by JohnEricson** [comment]
Thanks, I will get back to you on Skype.
